"""AI 跑团主持工具集——OpenAI/DeepSeek function-calling 格式。

工具 schema 按域拆到 `tool_defs_*`（combat/state/world/lookup），这里只做装配与再导出：
外部一律 `from backend.engine.tools import DM_TOOLS`，不要直接依赖具体分组模块。
新增工具时同时更新 `MODULE_TOOL_NAMES`（dm_agent）与 `tool_executor._handlers`。
"""
from backend.engine.tool_schemas import _tool  # noqa: F401
from backend.engine.tool_defs_combat import (  # noqa: F401
    DICE_ROLL_TOOL,
    COMBAT_ROUND_TOOL,
    ENEMY_ATTACK_TOOL,
    SAVE_DAMAGE_TOOL,
    SET_TACTICAL_STATE_TOOL,
    DEATH_SAVE_TOOL,
    REST_TOOL,
    ADVANCE_TIME_TOOL,
    EQUIP_ITEM_TOOL,
)
from backend.engine.tool_defs_state import (  # noqa: F401
    UPDATE_STATE_TOOL,
    GET_CHARACTER_STATE_TOOL,
    ADJUST_RESOURCE_TOOL,
    CAST_SPELL_TOOL,
    LEARN_SPELL_TOOL,
    FORGET_SPELL_TOOL,
)
from backend.engine.tool_defs_hazard import APPLY_HAZARD_TOOL  # noqa: F401
from backend.engine.tool_defs_trap import RESOLVE_TRAP_TOOL  # noqa: F401
from backend.engine.tool_defs_stealth import RESOLVE_STEALTH_TOOL  # noqa: F401
from backend.engine.tool_defs_contest import RESOLVE_CONTEST_TOOL  # noqa: F401
from backend.engine.tool_defs_poison import APPLY_POISON_TOOL  # noqa: F401
from backend.engine.tool_defs_chase import RESOLVE_CHASE_TOOL  # noqa: F401
from backend.engine.tool_defs_world import (  # noqa: F401
    ADD_MEMORY_TOOL,
    FORGET_MEMORY_TOOL,
    RECORD_PLOT_MEMORY_TOOL,
    SUGGEST_CHOICES_TOOL,
    UPDATE_WORLD_STATE_TOOL,
    PRUNE_WORLD_STATE_TOOL,
    REVEAL_INFO_TOOL,
    UPDATE_SCENE_TOOL,
    ADD_CHARACTER_NOTE_TOOL,
    UPDATE_BESTIARY_TOOL,
    UPDATE_CITY_TOOL,
    ADD_SCENARIO_BESTIARY_TOOL,
    ADD_SCENARIO_MAP_TOOL,
    ADD_SCENARIO_SPELL_TOOL,
    GENERATE_NAME_TOOL,
    ROLL_TREASURE_TOOL,
    NPC_QUIRK_TOOL,
)
from backend.engine.tool_defs_lookup import (  # noqa: F401
    SEARCH_KNOWLEDGE_TOOL,
    SEARCH_BESTIARY_TOOL,
    SEARCH_LOCATIONS_TOOL,
    SEARCH_SPELLS_TOOL,
    SEARCH_NPC_TOOL,
    ADJUST_NPC_TOOL,
    ADJUST_BESTIARY_TOOL,
    PROMOTE_NPC_TOOL,
    GET_BESTIARY_CARD_TOOL,
    GET_LOCATION_CARD_TOOL,
    GET_ENTITY_GRAPH_TOOL,
    UPDATE_KNOWLEDGE_GRAPH_TOOL,
    GET_GRAPH_PATH_TOOL,
    SEARCH_MEMORY_TOOL,
)

# 顺序 = 拆分前 `tools.py` 里的原始顺序：工具列表直接进模型提示，重排会改变模型注意力分布，
# 所以分组只体现在 import 与文件边界上，DM_TOOLS 本身保持原样。
DM_TOOLS = [
    DICE_ROLL_TOOL, UPDATE_STATE_TOOL, COMBAT_ROUND_TOOL, ENEMY_ATTACK_TOOL,
    DEATH_SAVE_TOOL, REST_TOOL, ADVANCE_TIME_TOOL, EQUIP_ITEM_TOOL, ADD_MEMORY_TOOL, RECORD_PLOT_MEMORY_TOOL, SUGGEST_CHOICES_TOOL,
    UPDATE_WORLD_STATE_TOOL, PRUNE_WORLD_STATE_TOOL, REVEAL_INFO_TOOL, UPDATE_SCENE_TOOL,
    ADD_CHARACTER_NOTE_TOOL, UPDATE_BESTIARY_TOOL, UPDATE_CITY_TOOL,
    ADD_SCENARIO_BESTIARY_TOOL, ADD_SCENARIO_MAP_TOOL, ADD_SCENARIO_SPELL_TOOL,
    GENERATE_NAME_TOOL, ROLL_TREASURE_TOOL, NPC_QUIRK_TOOL, SEARCH_KNOWLEDGE_TOOL,
    SEARCH_BESTIARY_TOOL, SEARCH_LOCATIONS_TOOL, SEARCH_SPELLS_TOOL,
    GET_CHARACTER_STATE_TOOL, ADJUST_RESOURCE_TOOL, CAST_SPELL_TOOL, SAVE_DAMAGE_TOOL,
    SET_TACTICAL_STATE_TOOL,
    APPLY_HAZARD_TOOL, RESOLVE_TRAP_TOOL, RESOLVE_STEALTH_TOOL, RESOLVE_CONTEST_TOOL,
    APPLY_POISON_TOOL,
    RESOLVE_CHASE_TOOL,
    LEARN_SPELL_TOOL, FORGET_SPELL_TOOL, SEARCH_NPC_TOOL, ADJUST_NPC_TOOL,
    ADJUST_BESTIARY_TOOL, PROMOTE_NPC_TOOL, GET_BESTIARY_CARD_TOOL, GET_LOCATION_CARD_TOOL,
    GET_ENTITY_GRAPH_TOOL, UPDATE_KNOWLEDGE_GRAPH_TOOL, GET_GRAPH_PATH_TOOL,
    SEARCH_MEMORY_TOOL,
    FORGET_MEMORY_TOOL,
]
