"""内置经典生物与常见城市背景（按规则系统隔离，内容丰富可扩展）。"""

CLASSIC_BESTIARY = [
    # ── D&D 5e ──
    {"name": "地精（Goblin）", "system": "dnd5e", "description": "矮小、狡诈、成群行动的人形生物，喜欢伏击与逃跑。", "stats": {"HP": 7, "AC": 15, "速度": "30尺", "攻击": "短剑/短弓", "挑战等级": "1/4"}, "tags": ["人形生物", "经典"], "details": {"habits": "昼伏夜出，喜欢设陷阱、偷窃和以多欺少。", "habitat": "洞穴、废墟、森林边缘", "lore": "地精往往被更强大的生物驱赶或奴役。", "weakness": "士气低落，首领死亡后容易溃散。"}},
    {"name": "兽人（Orc）", "system": "dnd5e", "description": "强壮野蛮的战士，崇尚力量与战争。", "stats": {"HP": 15, "AC": 13, "速度": "30尺", "攻击": "巨斧", "挑战等级": "1/2"}, "tags": ["人形生物", "经典"], "details": {"habits": "崇尚战功，劫掠商队和村庄。", "habitat": "山地、荒野、废城", "lore": "兽人战士以伤疤为荣耀。", "weakness": "容易在失去领袖时陷入内讧。"}},
    {"name": "骷髅（Skeleton）", "system": "dnd5e", "description": "被亡灵魔法驱动的骸骨，不知疲倦地服从主人。", "stats": {"HP": 13, "AC": 13, "速度": "30尺", "攻击": "短剑/短弓", "挑战等级": "1/4"}, "tags": ["亡灵", "经典"], "details": {"habits": "按命令巡逻、守卫、攻击一切活物。", "habitat": "墓穴、废弃城堡、死灵法师巢穴", "lore": "骷髅没有记忆与恐惧，只会执行指令。", "weakness": "钝击伤害优势；被神圣力量摧毁。"}},
    {"name": "僵尸（Zombie）", "system": "dnd5e", "description": "缓慢但顽强的行尸，只有摧毁头部或烧成灰烬才能停止。", "stats": {"HP": 22, "AC": 8, "速度": "20尺", "攻击": "挥击", "挑战等级": "1/4"}, "tags": ["亡灵", "经典"], "details": {"habits": "成群漫游，追捕活物。", "habitat": "疫病区、墓园、沼泽", "lore": "僵尸由死灵法术或瘟疫创造。", "weakness": "火焰和光耀伤害；速度极慢。"}},
    {"name": "红龙雏龙（Red Dragon Wyrmling）", "system": "dnd5e", "description": "暴虐红龙的幼体，已经具备喷吐火焰的危险本能。", "stats": {"HP": 75, "AC": 17, "速度": "30尺/飞行60尺", "攻击": "啃咬/爪击/火焰吐息", "挑战等级": "4"}, "tags": ["龙", "经典"], "details": {"habits": "贪婪、傲慢，喜欢收集闪亮物品。", "habitat": "火山、高山洞窟", "lore": "红龙以火焰和暴政闻名。", "weakness": "对寒冷伤害较脆弱（相对其他龙）。"}},
    {"name": "眼魔（Beholder）", "system": "dnd5e", "description": "漂浮的恐怖球体，中央巨眼与十根眼梗能释放多种魔法射线。", "stats": {"HP": 180, "AC": 18, "速度": "飞行20尺", "攻击": "啃咬/射线", "挑战等级": "13"}, "tags": ["异怪", "经典"], "details": {"habits": "极端自恋，建立地下巢穴奴役仆从。", "habitat": "幽暗地域、漂浮城堡", "lore": "眼魔认为自己是宇宙中心。", "weakness": "反魔法力场能压制其射线。"}},
    {"name": "狗头人（Kobold）", "system": "dnd5e", "description": "弱小但狡猾的爬虫类人生物，擅长陷阱与集群战术。", "stats": {"HP": 5, "AC": 12, "速度": "30尺", "攻击": "匕首/投石索", "挑战等级": "1/8"}, "tags": ["人形生物", "经典"], "details": {"habits": "挖掘隧道、设陷阱、崇拜龙类。", "habitat": "矿洞、地下城", "lore": "狗头人相信自己是龙的后裔。", "weakness": "阳光敏感；单独作战时很脆弱。"}},
    {"name": "巨魔（Troll）", "system": "dnd5e", "description": "再生能力极强的丑陋巨兽，酸与火才能阻止其恢复。", "stats": {"HP": 84, "AC": 15, "速度": "30尺", "攻击": "啃咬/爪击", "挑战等级": "5"}, "tags": ["巨人", "经典"], "details": {"habits": "独居或小群，捕食一切能抓住的生物。", "habitat": "桥下、沼泽、山地", "lore": "巨魔被切断的肢体仍会继续攻击。", "weakness": "火焰与强酸可抑制再生。"}},
    {"name": "幽影（Shadow）", "system": "dnd5e", "description": "由黑暗与负能量构成的虚体亡灵，会吸取力量。", "stats": {"HP": 16, "AC": 12, "速度": "飞行40尺", "攻击": "力量吸取", "挑战等级": "1/2"}, "tags": ["亡灵", "经典"], "details": {"habits": "潜伏在阴影中，袭击落单者。", "habitat": "暗巷、地下城、被诅咒之地", "lore": "幽影是强烈怨恨的残片。", "weakness": "光亮会削弱其隐匿；魔法武器才能有效命中。"}},
    {"name": "狮鹫（Griffon）", "system": "dnd5e", "description": "狮身鹰首的猛兽，常被驯化为坐骑。", "stats": {"HP": 59, "AC": 12, "速度": "30尺/飞行80尺", "攻击": "喙/爪", "挑战等级": "2"}, "tags": ["野兽", "经典"], "details": {"habits": "在高山筑巢，捕食马匹和牲畜。", "habitat": "高山、悬崖", "lore": "狮鹫忠诚但桀骜。", "weakness": "对空中机动目标优势明显；被擒获后难以驯服。"}},
    # ── D&D 4e ──
    {"name": "地精战士（Goblin Warrior）", "system": "dnd4e", "description": "4e 中的一级散兵，行动迅捷，擅长群体围攻。", "stats": {"HP": 29, "AC": 16, "强韧": 12, "反射": 14, "意志": 11, "攻击": "短剑", "等级": 1, "经验": 100}, "tags": ["人形生物", "4e经典"], "details": {"habits": "利用机动与地形进行游击。", "habitat": "洞穴、废墟", "lore": "地精战士通常成群出现。", "weakness": "HP 较低，适合快速击杀。"}},
    {"name": "兽人苦工（Orc Drudge）", "system": "dnd4e", "description": "4e 中的炮灰级兽人，数量众多，攻击凶猛。", "stats": {"HP": 1, "AC": 13, "强韧": 14, "反射": 11, "意志": 10, "攻击": "巨棒", "等级": 1, "经验": 25}, "tags": ["人形生物", "4e经典"], "details": {"habits": "成群冲锋，用数量淹没敌人。", "habitat": "战地、营地", "lore": "兽人苦工是兽人部落的消耗品。", "weakness": "HP 只有 1，属于“杂兵”。"}},
    {"name": "骷髅（Skeleton）", "system": "dnd4e", "description": "4e 亡灵生物，常见于墓穴与废弃城堡。", "stats": {"HP": 30, "AC": 16, "强韧": 13, "反射": 14, "意志": 12, "攻击": "长剑", "等级": 2, "经验": 125}, "tags": ["亡灵", "4e经典"], "details": {"habits": "守卫墓穴，服从召唤者。", "habitat": "地下城、墓园", "lore": "4e 骷髅比 5e 更耐打。", "weakness": "钝击与光耀伤害。"}},
    {"name": "幼龙（Young Dragon）", "system": "dnd4e", "description": "4e 中已具备飞行与吐息威能的年轻龙类。", "stats": {"HP": 150, "AC": 20, "强韧": 18, "反射": 16, "意志": 17, "攻击": "啃咬/爪击/吐息", "等级": 6, "经验": 500}, "tags": ["龙", "4e经典"], "details": {"habits": "占据领地，收集财宝。", "habitat": "高山巢穴", "lore": "幼龙已能使用遭遇威能。", "weakness": "年轻，经验不足。"}},
    {"name": "兽人狂战士（Orc Berserker）", "system": "dnd4e", "description": "4e 中进入狂暴状态的兽人，攻击极其危险。", "stats": {"HP": 46, "AC": 15, "强韧": 16, "反射": 13, "意志": 12, "攻击": "巨斧", "等级": 3, "经验": 150}, "tags": ["人形生物", "4e经典"], "details": {"habits": "受伤后更加疯狂。", "habitat": "战场、掠夺队", "lore": "狂战士不畏惧死亡。", "weakness": "防御较低。"}},
    # ── COC 7e ──
    {"name": "深潜者（Deep One）", "system": "coc", "description": "两栖人形生物，崇拜达贡与海德拉，能与人类繁衍并逐渐变异。", "stats": {"HP": 11, "MP": 10, "伤害加值": "+1d4", "护甲": 1, "技能": "格斗50%", "理智损失": "0/1d6"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "夜间上岸，举行水下仪式。", "habitat": "海岸、海底城市", "lore": "与深潜者接触的人会逐渐变成它们。", "weakness": "离开水后行动受限。"}},
    {"name": "米·戈（Mi-Go）", "system": "coc", "description": "来自犹格斯星的真菌类智慧生物，拥有先进科技与飞行能力。", "stats": {"HP": 13, "MP": 10, "伤害加值": "+1d6", "护甲": 4, "技能": "格斗40%", "理智损失": "0/1d6"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "采集人类大脑样本进行研究。", "habitat": "深山、太空、实验室", "lore": "米·戈能进行星际旅行。", "weakness": "高温和火焰能伤害其真菌躯体。"}},
    {"name": "修格斯（Shoggoth）", "system": "coc", "description": "由古老者创造的巨型变形生物，遍布眼睛与口器，吞噬一切。", "stats": {"HP": 40, "MP": 15, "伤害加值": "+6d6", "护甲": 6, "技能": "格斗80%", "理智损失": "1d3/1d10"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "在黑暗中缓慢移动，吞噬有机体。", "habitat": "海底遗迹、深渊", "lore": "修格斯是古老者的造物，后来背叛了主人。", "weakness": "强光和电能可能使其混乱。"}},
    {"name": "次元潜行者（Dimensional Shambler）", "system": "coc", "description": "能穿越维度的恐怖生物，常将受害者拖入未知空间。", "stats": {"HP": 16, "MP": 10, "伤害加值": "+1d6", "护甲": 2, "技能": "格斗55%", "理智损失": "1d3/1d20"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "潜伏在维度裂缝附近，狩猎孤立者。", "habitat": "异次元、废弃建筑", "lore": "它们能凭空消失并带走猎物。", "weakness": "难以被常规武器追踪。"}},
    {"name": "食尸鬼（Ghoul）", "system": "coc", "description": "以尸体为食的堕落人类，在地底城市中群居。", "stats": {"HP": 12, "MP": 8, "伤害加值": "0", "护甲": 0, "技能": "格斗45%", "理智损失": "0/1d6"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "夜间掘墓觅食。", "habitat": "墓园、地底通道", "lore": "食尸鬼能说人类语言，但已完全异化。", "weakness": "强光与神圣象征。"}},
    {"name": "星之眷族（Star Spawn）", "system": "coc", "description": "克苏鲁的仆从种族，巨大、畸形、充满恶意。", "stats": {"HP": 30, "MP": 18, "伤害加值": "+4d6", "护甲": 4, "技能": "格斗70%", "理智损失": "1d6/1d20"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "侍奉克苏鲁，等待拉莱耶升起。", "habitat": "海底城市、梦境", "lore": "星之眷族是旧日支配者的后裔。", "weakness": "个体差异大，但大多畏惧强光。"}},
    {"name": "拜亚基（Byakhee）", "system": "coc", "description": "星际飞行生物，能载着骑手穿越宇宙。", "stats": {"HP": 14, "MP": 10, "伤害加值": "+1d4", "护甲": 2, "技能": "格斗45%", "理智损失": "0/1d6"}, "tags": ["神话生物", "COC经典"], "details": {"habits": "在寒冷太空与梦境中飞行。", "habitat": "星际空间、梦境", "lore": "拜亚基由黄衣之王信徒召唤。", "weakness": "在地球大气中不能长时间停留。"}},
]

COMMON_CITIES = [
    {"name": "深水城（Waterdeep）", "system": "dnd5e", "description": "剑湾的璀璨之城，被称为“北地的明珠”，由隐形领主治理。", "locations": [{"name": "港口区", "x": 0.8, "y": 0.5}, {"name": "城堡区", "x": 0.5, "y": 0.3}], "details": {"culture": "商业、冒险、行会文化浓厚。", "districts": ["港口区", "城堡区", "市场区", "神殿山"], "notable_figures": "隐形领主、凯尔本·奥罗桑", "dangers": "地下城与盗贼工会。"}},
    {"name": "博德之门（Baldur's Gate）", "system": "dnd5e", "description": "剑湾南部的大都市，商业繁荣但暗藏阴谋。", "locations": [{"name": "下城", "x": 0.5, "y": 0.6}, {"name": "上城", "x": 0.5, "y": 0.4}], "details": {"culture": "商人至上，铁手会维持治安。", "districts": ["下城", "上城", "外城"], "notable_figures": "公爵议会、铁手会", "dangers": "政治阴谋、街头帮派。"}},
    {"name": "无冬城（Neverwinter）", "system": "dnd5e", "description": "被誉为“北方明珠”的美丽城市，工匠技艺高超。", "locations": [{"name": "港口", "x": 0.7, "y": 0.6}, {"name": "城堡区", "x": 0.4, "y": 0.4}], "details": {"culture": "工匠行会、魔法与艺术。", "districts": ["港口", "城堡区", "匠城区"], "notable_figures": "纳萨拉·阿吉尔瓦恩、黎明之主教会", "dangers": "火山遗迹、地精与亡灵威胁。"}},
    {"name": "剑湾（Sword Coast）", "system": "dnd5e", "description": "费伦西部漫长的海岸线，散布着港口、废墟与冒险圣地。", "locations": [{"name": "北剑湾", "x": 0.5, "y": 0.3}, {"name": "南剑湾", "x": 0.5, "y": 0.7}], "details": {"culture": "冒险者文化、贸易路线。", "districts": ["路斯坎", "深水城", "博德之门", "贝尔苟斯特"], "notable_figures": "各地领主", "dangers": "海盗、兽人、怪物。"}},
    {"name": "浮影城（4e 风格 Waterdeep）", "system": "dnd4e", "description": "4e 设定下的剑湾大都会，拥有神秘的地下城与众多势力。", "locations": [{"name": "城门区", "x": 0.5, "y": 0.5}], "details": {"culture": "冒险者公会与势力博弈。", "districts": ["城门外", "下城", "上城"], "notable_figures": "隐形领主、各派系领袖", "dangers": "地脉怪物、政治暗杀。"}},
    {"name": "影之城（Shadowfell 4e）", "system": "dnd4e", "description": "4e 中与主物质位面平行的黑暗领域，亡灵与阴影横行。", "locations": [{"name": "阴影要塞", "x": 0.5, "y": 0.5}], "details": {"culture": "阴沉、失落文明。", "districts": ["哀嚎荒原", "阴影要塞", "遗忘之城"], "notable_figures": "暗影君主", "dangers": "亡灵、阴影生物。"}},
    {"name": "伊泽尔（4e 风格）", "system": "dnd4e", "description": "一座被龙类与战争撕裂的边境城市，适合4e冒险。", "locations": [{"name": "市场", "x": 0.6, "y": 0.5}], "details": {"culture": "军事化、龙类崇拜。", "districts": ["兵营", "市场", "王宫"], "notable_figures": "龙裔领主", "dangers": "龙类袭击。"}},
    {"name": "阿卡姆（Arkham）", "system": "coc", "description": "马萨诸塞州的新英格兰城镇，密斯卡托尼克大学所在地。", "locations": [{"name": "密斯卡托尼克大学", "x": 0.6, "y": 0.4}, {"name": "法国人区", "x": 0.5, "y": 0.6}], "details": {"culture": "学术、清教传统、禁忌知识。", "districts": ["大学区", "法国人区", "河滨区"], "notable_figures": "阿卡姆疯人院、密大教授", "dangers": "邪教、疯人院、深潜者传说。"}},
    {"name": "波士顿（Boston）", "system": "coc", "description": "1920年代的大都市，禁酒令、黑帮与古老秘密并存。", "locations": [{"name": "灯塔街", "x": 0.5, "y": 0.5}, {"name": "中央图书馆", "x": 0.6, "y": 0.4}], "details": {"culture": "现代与旧世界交织。", "districts": ["灯塔街", "北角", "查尔斯顿"], "notable_figures": "市政官员、黑帮、秘密结社", "dangers": "禁酒令暴力、神话事件。"}},
    {"name": "伦敦（London）", "system": "coc", "description": "维多利亚与战间期的大英帝国心脏，迷雾之下隐藏秘密。", "locations": [{"name": "白教堂", "x": 0.5, "y": 0.5}], "details": {"culture": "阶级分明、俱乐部文化。", "districts": ["白教堂", "西敏", "苏豪"], "notable_figures": "绅士侦探、神秘学团体", "dangers": "开膛手传说、地下邪教。"}},
    {"name": "敦威治（Dunwich）", "system": "coc", "description": "马萨诸塞州偏僻的荒凉村落，充满堕落与禁忌。", "locations": [{"name": "教堂", "x": 0.5, "y": 0.4}, {"name": "牧场", "x": 0.5, "y": 0.6}], "details": {"culture": "封闭、迷信、近亲通婚。", "districts": ["村落", "荒山", "河谷"], "notable_figures": "惠普尔家族、老惠普尔", "dangers": "禁忌实验、怪物。"}},
    {"name": "印斯茅斯（Innsmouth）", "system": "coc", "description": "衰败的海港小镇，居民带有鱼类的特征。", "locations": [{"name": "码头", "x": 0.7, "y": 0.5}, {"name": "礼拜堂", "x": 0.4, "y": 0.5}], "details": {"culture": "排外、崇拜大衮。", "districts": ["码头", "旧城区", "礁石"], "notable_figures": "马什家族", "dangers": "深潜者、秘密仪式。"}},
    {"name": "金斯波特（Kingsport）", "system": "coc", "description": "海边古镇，以诡异传说和梦境闻名。", "locations": [{"name": "港口", "x": 0.6, "y": 0.5}], "details": {"culture": "渔业、清教传统。", "districts": ["港口", "山丘", "灯塔"], "notable_figures": "古老家族", "dangers": "梦境生物、古老仪式。"}},
]
