"""法术库内置数据：学派/职业中文名与内置经典法术表。

从 backend/media_spells 拆出（那边只保留播种、增删改查与剧本同步逻辑）。
数据表变动频繁、与存取逻辑无关，单独成文件后两边都不会继续膨胀。
"""

_SCHOOL_CN = {
    "A": "防护", "C": "咒法", "D": "预言", "E": "塑能",
    "EN": "附魔", "I": "幻术", "N": "死灵", "T": "变化", "V": "预言",
}

_CLASS_CN = {
    "Wizard": "法师", "Sorcerer": "术士", "Warlock": "邪术师",
    "Cleric": "牧师", "Druid": "德鲁伊", "Bard": "吟游诗人",
    "Paladin": "圣武士", "Ranger": "游侠", "Artificer": "奇械师",
    "wizard": "法师", "sorcerer": "术士", "warlock": "邪术师",
    "cleric": "牧师", "druid": "德鲁伊", "bard": "吟游诗人",
    "paladin": "圣武士", "ranger": "游侠", "artificer": "奇械师",
}


# 内置经典法术：固定格式，name/level/school/ritual/casting_time/range/components/duration/classes/description
CLASSIC_SPELLS = [
    {"name": "火焰箭", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "你对施法距离内的一个生物或物件掷出一团火焰。进行一次远程法术攻击，命中则目标受到 1d10 点火焰伤害。未被着装或携带的可燃物件会被点燃。升环：5 级时伤害增至 2d10，11 级 3d10，17 级 4d10。"},
    {"name": "冷冻射线", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "一道蓝白色寒光射向目标。远程法术攻击命中后造成 1d8 点寒冷伤害，目标速度减少 10 尺直到你的下一回合开始。"},
    {"name": "魔法伎俩", "level": "0", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "10 尺", "components": "V、S", "duration": "至多 1 小时",
     "classes": ["吟游诗人", "术士", "邪术师", "法师"],
     "description": "制造简单魔法效果：点燃/熄灭蜡烛、清洁衣物、制造声响、改变味道等。同时维持的效果不超过三个。"},
    {"name": "法师之手", "level": "0", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V、S", "duration": "1 分钟",
     "classes": ["吟游诗人", "术士", "邪术师", "法师"],
     "description": "一只半透明漂浮手出现在范围内，可执行 10 磅以内物体的简单操作：开门、取物、倾倒药剂等。不能攻击、启动魔法物品或携带超过 10 磅。"},
    {"name": "次级幻影", "level": "0", "school": "幻术", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "S、M（一点羊毛）", "duration": "1 分钟",
     "classes": ["吟游诗人", "术士", "邪术师", "法师"],
     "description": "在范围内制造一个声音或一个物体的影像，持续到法术结束。影像不能移动，不能发出声音以外的效果。"},
    {"name": "魔能爆", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "立即",
     "classes": ["邪术师"],
     "description": "对目标进行远程法术攻击，命中造成 1d10 力场伤害。5 级时攻击次数增至两次，11 级三次，17 级四次。"},
    {"name": "圣火术", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S", "duration": "立即",
     "classes": ["牧师"],
     "description": "灼热圣光倾泻而下。目标必须通过敏捷豁免，否则受到 1d8 点光耀伤害。目标不能因掩蔽获得豁免优势。"},
    {"name": "荆棘之鞭", "level": "0", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V、S、M（一根荆棘藤）", "duration": "立即",
     "classes": ["德鲁伊"],
     "description": "藤蔓长鞭抽向目标。近战法术攻击命中造成 1d6 穿刺伤害，并可将目标向你拉近 10 尺。"},
    {"name": "恶言相加", "level": "0", "school": "附魔", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V", "duration": "立即",
     "classes": ["吟游诗人"],
     "description": "你对目标说出恶毒咒语。目标必须通过感知豁免，否则受到 1d4 心灵伤害，且下一次攻击检定有劣势。"},
    {"name": "奇术", "level": "0", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V", "duration": "至多 1 分钟",
     "classes": ["牧师", "提夫林"],
     "description": "制造一个低语般的神迹：声音放大、火焰变色、地面颤动或双眼发光，用于威慑与宣告。"},
    {"name": "神导术", "level": "0", "school": "预言", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S", "duration": "专注，至多 1 分钟",
     "classes": ["牧师", "德鲁伊"],
     "description": "触及的自愿生物在随后的一次属性检定中获得 1d4 加值。"},
    {"name": "德鲁伊伎俩", "level": "0", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V、S", "duration": "立即",
     "classes": ["德鲁伊"],
     "description": "与自然沟通的小把戏：预测天气、让花朵绽放、点燃/熄灭篝火、制造兽鸣。"},
    {"name": "电爪", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "手中跃出闪电。近战法术攻击命中造成 1d8 闪电伤害，目标在你的下一回合开始前不能进行借机攻击。"},
    {"name": "魔法飞弹", "level": "1", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "三枚魔法飞镖自动命中施法距离内的目标，每枚造成 1d4+1 力场伤害。飞镖可分配不同目标。升环：每高一环多一枚飞镖。"},
    {"name": "法师护甲", "level": "1", "school": "防护", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S、M（一小块鞣制皮革）", "duration": "8 小时",
     "classes": ["术士", "法师"],
     "description": "目标未着甲时，其基础 AC 变为 13+敏捷调整。目标着甲或法术结束时终止。"},
    {"name": "护盾术", "level": "1", "school": "防护", "ritual": False,
     "casting_time": "1 反应（被击中时）", "range": "自身", "components": "V、S", "duration": "1 轮",
     "classes": ["术士", "法师"],
     "description": "隐形力场护盾出现，直到你的下一回合开始 AC+5，且免疫魔法飞弹。"},
    {"name": "燃烧之手", "level": "1", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "自身（15 尺锥形）", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "火焰从指尖喷出，15 尺锥形范围内生物必须通过敏捷豁免，失败受到 3d6 火焰伤害，成功减半。升环：每高一环 +1d6。"},
    {"name": "治愈真言", "level": "1", "school": "塑能", "ritual": False,
     "casting_time": "1 附赠动作", "range": "60 尺", "components": "V", "duration": "立即",
     "classes": ["牧师", "吟游诗人"],
     "description": "施法距离内可见的一个生物恢复 1d4+施法属性调整点生命值。对构装体和不死生物无效。升环：每高一环 +1d4。"},
    {"name": "治疗伤害", "level": "1", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S", "duration": "立即",
     "classes": ["牧师", "德鲁伊", "圣武士", "游侠"],
     "description": "触及的生物恢复 1d8+施法属性调整点生命值。对构装体和不死生物无效。升环：每高一环 +1d8。"},
    {"name": "祝福术", "level": "1", "school": "附魔", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V、S、M（一点圣水）", "duration": "专注，至多 1 分钟",
     "classes": ["牧师", "圣武士"],
     "description": "至多三个生物在攻击检定和豁免检定时获得 1d4 加值。"},
    {"name": "侦测魔法", "level": "1", "school": "预言", "ritual": True,
     "casting_time": "1 动作", "range": "自身", "components": "V、S", "duration": "专注，至多 10 分钟",
     "classes": ["吟游诗人", "牧师", "德鲁伊", "圣武士", "游侠", "术士", "邪术师", "法师"],
     "description": "你能感知 30 尺内的魔法与魔法物品，并用动作辨识其学派。"},
    {"name": "隐形术", "level": "2", "school": "幻术", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S、M（一根包裹在阿拉伯胶中的睫毛）", "duration": "专注，至多 1 小时",
     "classes": ["吟游诗人", "术士", "邪术师", "法师"],
     "description": "触及的生物连同随身物品变为隐形，直到其攻击或施法。"},
    {"name": "灼热射线", "level": "2", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "射出三道火焰射线，每道进行一次远程法术攻击，命中造成 2d6 火焰伤害。升环：每高一环多一道射线。"},
    {"name": "迷踪步", "level": "2", "school": "咒法", "ritual": False,
     "casting_time": "1 附赠动作", "range": "自身", "components": "V", "duration": "立即",
     "classes": ["术士", "邪术师", "法师"],
     "description": "你被银色雾气包裹，瞬间传送到 30 尺内可见的未占据空间。"},
    {"name": "火球术", "level": "3", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "150 尺", "components": "V、S、M（一小球蝙蝠粪及硫磺）", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "明亮的闪光从你的指间飞驰向施法距离内你指定的一点，并随着一声低吼迸成一片烈焰。目标点周围半径 20 尺球状区域内的每个生物必须进行一次敏捷豁免。豁免失败者将受到 8d6 点火焰伤害，豁免成功则伤害减半。迸发的火焰将绕过拐角扩散，并点燃区域内所有未被着装或携带的可燃物件。升环：使用 4 环或更高法术位施放时，每比 3 环高一环，伤害增加 1d6。"},
    {"name": "闪电束", "level": "3", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "自身（100 尺线状）", "components": "V、S、M（一点毛皮和一根琥珀/水晶棒）", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "一道 100 尺长、5 尺宽的闪电从你指向的方向射出，线上生物敏捷豁免失败受到 8d6 闪电伤害，成功减半。升环：每高一环 +1d6。"},
    {"name": "反制法术", "level": "3", "school": "防护", "ritual": False,
     "casting_time": "1 反应", "range": "60 尺", "components": "S", "duration": "立即",
     "classes": ["术士", "邪术师", "法师"],
     "description": "打断一个正在施放的法术。若目标法术环位不高于你使用的法术位，该法术失效。高于则进行施法属性检定，DC=10+目标法术环位。"},
    {"name": "飞行术", "level": "3", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S、M（任意鸟类的翼羽）", "duration": "专注，至多 10 分钟",
     "classes": ["术士", "邪术师", "法师"],
     "description": "触及的自愿生物获得 60 尺飞行速度。升环：每高一环可多影响一个生物。"},
    {"name": "冰风暴", "level": "4", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "300 尺", "components": "V、S、M（一点灰尘和几滴水）", "duration": "立即",
     "classes": ["德鲁伊", "术士", "法师"],
     "description": "以目标点为中心 20 尺半径、40 尺高的圆柱区域内降下冰雹，生物受到 2d8 钝击+4d6 寒冷伤害（敏捷豁免成功减半），区域变为困难地形直到你的下一回合结束。"},
    {"name": "寒冰锥", "level": "5", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "自身（60 尺锥形）", "components": "V、S、M（一小块水晶或玻璃锥体）", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "60 尺锥形寒流爆发，范围内生物体质豁免失败受到 8d8 寒冷伤害，成功减半。豁免失败的生物若 HP 因此归零会被冻成冰雕。升环：每高一环 +1d8。"},
]

# ── 追加更多内置经典法术 ──
CLASSIC_SPELLS += [
    {"name": "光亮术", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、M（一只萤火虫或磷光苔藓）", "duration": "1 小时",
     "classes": ["吟游诗人", "牧师", "法师"],
     "description": "触及的物体发出 20 尺半径明亮光芒和额外 20 尺微光。可指定颜色；反黑暗术可以压过它。"},
    {"name": "舞光术", "level": "0", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S、M（一点磷火或发磷光的真菌）", "duration": "专注，至多 1 分钟",
     "classes": ["吟游诗人", "术士", "法师"],
     "description": "在范围内创造至多四团火光，可合并或拆散，并可按你指定方向缓慢移动。"},
    {"name": "毒液喷溅", "level": "0", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S", "duration": "立即",
     "classes": ["德鲁伊", "术士", "邪术师", "法师"],
     "description": "向目标喷出毒液。目标必须通过体质豁免，失败受到 1d12 毒素伤害，成功则不受伤害。升环：5 级时 2d12，11 级 3d12，17 级 4d12。"},
    {"name": "油腻术", "level": "1", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S、M（一块猪油或黄油）", "duration": "1 分钟",
     "classes": ["术士", "法师"],
     "description": "以一点为中心 10 尺见方区域覆盖油脂，变为困难地形。区域内生物倒地时进行敏捷豁免，失败则倒地。"},
    {"name": "魔法武器", "level": "1", "school": "变化", "ritual": False,
     "casting_time": "1 附赠动作", "range": "触及", "components": "V、S", "duration": "专注，至多 1 小时",
     "classes": ["牧师", "圣武士"],
     "description": "触及的一件非魔法武器变为魔法武器，攻击与伤害检定获得 +1 加值。升环：4 环 +2，6 环 +3。"},
    {"name": "侦测善恶", "level": "1", "school": "预言", "ritual": False,
     "casting_time": "1 动作", "range": "自身", "components": "V、S", "duration": "专注，至多 10 分钟",
     "classes": ["牧师", "圣武士"],
     "description": "感知 30 尺内是否存在天界生物、邪魔、不死生物或强烈邪恶/善良灵光。"},
    {"name": "脚底抹油", "level": "1", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S、M（一滴油）", "duration": "1 小时",
     "classes": ["吟游诗人", "术士", "法师"],
     "description": "触及生物速度增加 30 尺。升环：每高一环可多影响一个生物。"},
    {"name": "云雾术", "level": "1", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "专注，至多 1 小时",
     "classes": ["德鲁伊", "游侠", "术士", "法师"],
     "description": "以一点为中心 20 尺半径形成浓雾，区域重度遮蔽。强风可提前驱散。"},
    {"name": "灼热金属", "level": "2", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S、M（一块铁片）", "duration": "专注，至多 1 分钟",
     "classes": ["德鲁伊"],
     "description": "区域内一件金属物体变得灼热。持握者受到 2d8 火焰伤害，每回合可用动作再造成伤害。"},
    {"name": "黑暗术", "level": "2", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、M（蝙蝠粪与一滴焦油）", "duration": "专注，至多 10 分钟",
     "classes": ["邪术师", "法师"],
     "description": "以一点为中心 15 尺半径魔法黑暗，黑暗视觉无法看穿。光亮术无法照亮。"},
    {"name": "蛛网术", "level": "2", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S、M（一点蛛网）", "duration": "专注，至多 1 小时",
     "classes": ["术士", "法师"],
     "description": "以一点为中心 20 尺立方区域布满粘稠蛛网，区域为困难地形。被困生物可用力量检定挣脱。"},
    {"name": "次级复原术", "level": "2", "school": "防护", "ritual": False,
     "casting_time": "1 动作", "range": "触及", "components": "V、S", "duration": "立即",
     "classes": ["吟游诗人", "牧师", "德鲁伊"],
     "description": "治愈疾病、中毒、麻痹、耳聋或目盲等一种状态。升环：每高一环可多治愈一个生物。"},
    {"name": "恐惧术", "level": "3", "school": "幻术", "ritual": False,
     "casting_time": "1 动作", "range": "自身（30 尺锥形）", "components": "V、S、M（一根白羽毛）", "duration": "专注，至多 1 分钟",
     "classes": ["吟游诗人", "术士", "邪术师", "法师"],
     "description": "30 尺锥形范围内生物感知豁免失败则陷入恐慌，每回合尝试逃离并投弃武器。"},
    {"name": "加速术", "level": "3", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "30 尺", "components": "V、S、M（一根甘草根）", "duration": "专注，至多 1 分钟",
     "classes": ["术士", "法师"],
     "description": "目标速度翻倍，AC +2，敏捷豁免优势，每回合可多进行一次动作（攻击/疾走/躲藏等）。"},
    {"name": "解除魔法", "level": "3", "school": "防护", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S", "duration": "立即",
     "classes": ["吟游诗人", "牧师", "德鲁伊", "圣武士", "术士", "邪术师", "法师"],
     "description": "终止目标范围内一个生物或物体上的法术效果。对法术效果需要进行施法属性检定。"},
    {"name": "火墙术", "level": "4", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "120 尺", "components": "V、S、M（一小块硫磺）", "duration": "专注，至多 1 分钟",
     "classes": ["德鲁伊", "术士", "法师"],
     "description": "创造一道 60 尺长、20 尺高的火焰之墙，穿过或位于其中者受到 5d8 火焰伤害，成功豁免减半。"},
    {"name": "变形术", "level": "4", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "60 尺", "components": "V、S、M（一根毛虫茧）", "duration": "专注，至多 1 小时",
     "classes": ["吟游诗人", "德鲁伊", "术士", "法师"],
     "description": "将自愿生物变为挑战等级不超过其等级/命中骰的野兽形态，获得其游戏数据。"},
    {"name": "闪电链", "level": "5", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "150 尺", "components": "V、S、M（一根银线）", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "闪电击中一个目标，随后跳跃至附近至多三个目标。每次命中造成 10d8 闪电伤害。升环：每高一环 +1d8。"},
    {"name": "传送术", "level": "7", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "10 尺", "components": "V", "duration": "立即",
     "classes": ["吟游诗人", "术士", "法师"],
     "description": "将自身与同伴瞬间传送到已知地点。到达陌生地点时可能偏移或发生事故。"},
    {"name": "虹光喷射", "level": "7", "school": "塑能", "ritual": False,
     "casting_time": "1 动作", "range": "自身（60 尺锥形）", "components": "V、S", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "七色光芒从手中射出，每道颜色对应不同效果（火焰、强酸、闪电、毒素、寒冷、石化、昏迷）。"},
    {"name": "时间停止", "level": "9", "school": "变化", "ritual": False,
     "casting_time": "1 动作", "range": "自身", "components": "V", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "时间为你停止，你获得 1d4+1 轮额外回合，可进行移动与动作但不能影响其他生物。"},
    {"name": "祈愿术", "level": "9", "school": "咒法", "ritual": False,
     "casting_time": "1 动作", "range": "自身", "components": "V", "duration": "立即",
     "classes": ["术士", "法师"],
     "description": "描述一个愿望，DM 可尽量满足。非标准愿望可能产生意外代价，并施法者承受压力。"},
]


_CLASSIC_SPELL_NAMES = {s["name"] for s in CLASSIC_SPELLS}
