"""SRD 法术职业映射（自动生成自 5etools PHB 数据，离线使用）。"""

SRD_SPELL_CLASSES = {
    'Acid Splash': ['术士', '法师'],
    'Aid': ['牧师', '圣武士', '奇械师'],
    'Alarm': ['游侠', '法师', '奇械师'],
    'Alter Self': ['术士', '法师', '奇械师'],
    'Animal Friendship': ['吟游诗人', '德鲁伊', '游侠'],
    'Animal Messenger': ['吟游诗人', '德鲁伊', '游侠'],
    'Animal Shapes': ['德鲁伊'],
    'Animate Dead': ['牧师', '法师'],
    'Animate Objects': ['吟游诗人', '术士', '法师'],
    'Antilife Shell': ['德鲁伊'],
    'Antimagic Field': ['牧师', '法师'],
    'Antipathy/Sympathy': ['德鲁伊', '法师'],
    'Arcane Eye': ['法师', '奇械师'],
    'Arcane Gate': ['术士', '邪术师', '法师'],
    'Arcane Lock': ['法师', '奇械师'],
    'Armor of Agathys': ['邪术师'],
    'Arms of Hadar': ['邪术师'],
    'Astral Projection': ['牧师', '邪术师', '法师'],
    'Augury': ['牧师'],
    'Aura of Life': ['圣武士'],
    'Aura of Purity': ['圣武士'],
    'Aura of Vitality': ['圣武士'],
    'Awaken': ['吟游诗人', '德鲁伊'],
    'Bane': ['吟游诗人', '牧师'],
    'Banishing Smite': ['圣武士'],
    'Banishment': ['牧师', '圣武士', '术士', '邪术师', '法师'],
    'Barkskin': ['德鲁伊', '游侠'],
    'Beacon of Hope': ['牧师'],
    'Beast Sense': ['德鲁伊', '游侠'],
    'Bestow Curse': ['吟游诗人', '牧师', '法师'],
    "Bigby's Hand": ['法师'],
    'Blade Barrier': ['牧师'],
    'Blade Ward': ['吟游诗人', '术士', '邪术师', '法师'],
    'Bless': ['牧师', '圣武士'],
    'Blight': ['德鲁伊', '术士', '邪术师', '法师'],
    'Blinding Smite': ['圣武士'],
    'Blindness/Deafness': ['吟游诗人', '牧师', '术士', '法师'],
    'Blink': ['术士', '法师', '奇械师'],
    'Blur': ['术士', '法师', '奇械师'],
    'Branding Smite': ['圣武士'],
    'Burning Hands': ['术士', '法师'],
    'Call Lightning': ['德鲁伊'],
    'Calm Emotions': ['吟游诗人', '牧师'],
    'Chain Lightning': ['术士', '法师'],
    'Charm Person': ['吟游诗人', '德鲁伊', '术士', '邪术师', '法师'],
    'Chill Touch': ['术士', '邪术师', '法师'],
    'Chromatic Orb': ['术士', '法师'],
    'Circle of Death': ['术士', '邪术师', '法师'],
    'Circle of Power': ['圣武士'],
    'Clairvoyance': ['吟游诗人', '牧师', '术士', '法师'],
    'Clone': ['法师'],
    'Cloud of Daggers': ['吟游诗人', '术士', '邪术师', '法师'],
    'Cloudkill': ['术士', '法师'],
    'Color Spray': ['术士', '法师'],
    'Command': ['牧师', '圣武士'],
    'Commune': ['牧师'],
    'Commune with Nature': ['德鲁伊', '游侠'],
    'Compelled Duel': ['圣武士'],
    'Comprehend Languages': ['吟游诗人', '术士', '邪术师', '法师'],
    'Compulsion': ['吟游诗人'],
    'Cone of Cold': ['术士', '法师'],
    'Confusion': ['吟游诗人', '德鲁伊', '术士', '法师'],
    'Conjure Animals': ['德鲁伊', '游侠'],
    'Conjure Barrage': ['游侠'],
    'Conjure Celestial': ['牧师'],
    'Conjure Elemental': ['德鲁伊', '法师'],
    'Conjure Fey': ['德鲁伊', '邪术师'],
    'Conjure Minor Elementals': ['德鲁伊', '法师'],
    'Conjure Volley': ['游侠'],
    'Conjure Woodland Beings': ['德鲁伊', '游侠'],
    'Contact Other Plane': ['邪术师', '法师'],
    'Contagion': ['牧师', '德鲁伊'],
    'Contingency': ['法师'],
    'Continual Flame': ['牧师', '法师', '奇械师'],
    'Control Water': ['牧师', '德鲁伊', '法师'],
    'Control Weather': ['牧师', '德鲁伊', '法师'],
    'Cordon of Arrows': ['游侠'],
    'Counterspell': ['术士', '邪术师', '法师'],
    'Create Food and Water': ['牧师', '圣武士'],
    'Create Undead': ['牧师', '邪术师', '法师'],
    'Create or Destroy Water': ['牧师', '德鲁伊'],
    'Creation': ['术士', '法师'],
    'Crown of Madness': ['吟游诗人', '术士', '邪术师', '法师'],
    "Crusader's Mantle": ['圣武士'],
    'Cure Wounds': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '游侠', '奇械师'],
    'Dancing Lights': ['吟游诗人', '术士', '法师'],
    'Darkness': ['术士', '邪术师', '法师'],
    'Darkvision': ['德鲁伊', '游侠', '术士', '法师', '奇械师'],
    'Daylight': ['牧师', '德鲁伊', '圣武士', '游侠', '术士'],
    'Death Ward': ['牧师', '圣武士', '奇械师'],
    'Delayed Blast Fireball': ['术士', '法师'],
    'Demiplane': ['邪术师', '法师'],
    'Destructive Wave': ['圣武士'],
    'Detect Evil and Good': ['牧师', '圣武士'],
    'Detect Magic': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '游侠', '术士', '法师'],
    'Detect Poison and Disease': ['牧师', '德鲁伊', '圣武士', '游侠'],
    'Detect Thoughts': ['吟游诗人', '术士', '法师'],
    'Dimension Door': ['吟游诗人', '术士', '邪术师', '法师'],
    'Disguise Self': ['吟游诗人', '术士', '法师', '奇械师'],
    'Disintegrate': ['术士', '法师'],
    'Dispel Evil and Good': ['牧师', '圣武士'],
    'Dispel Magic': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '术士', '邪术师', '法师'],
    'Dissonant Whispers': ['吟游诗人'],
    'Divination': ['牧师'],
    'Divine Favor': ['圣武士'],
    'Divine Word': ['牧师'],
    'Dominate Beast': ['德鲁伊', '术士'],
    'Dominate Monster': ['吟游诗人', '术士', '邪术师', '法师'],
    'Dominate Person': ['吟游诗人', '术士', '法师'],
    "Drawmij's Instant Summons": ['法师'],
    'Dream': ['吟游诗人', '邪术师', '法师'],
    'Druidcraft': ['德鲁伊'],
    'Earthquake': ['牧师', '德鲁伊', '术士'],
    'Eldritch Blast': ['邪术师'],
    'Elemental Weapon': ['圣武士'],
    'Enhance Ability': ['吟游诗人', '牧师', '德鲁伊', '术士', '奇械师'],
    'Enlarge/Reduce': ['术士', '法师', '奇械师'],
    'Ensnaring Strike': ['游侠'],
    'Entangle': ['德鲁伊'],
    'Enthrall': ['吟游诗人', '邪术师'],
    'Etherealness': ['吟游诗人', '牧师', '术士', '邪术师', '法师'],
    "Evard's Black Tentacles": ['法师'],
    'Expeditious Retreat': ['术士', '邪术师', '法师', '奇械师'],
    'Eyebite': ['吟游诗人', '术士', '邪术师', '法师'],
    'Fabricate': ['法师', '奇械师'],
    'Faerie Fire': ['吟游诗人', '德鲁伊'],
    'False Life': ['术士', '法师', '奇械师'],
    'Fear': ['吟游诗人', '术士', '邪术师', '法师'],
    'Feather Fall': ['吟游诗人', '术士', '法师'],
    'Feeblemind': ['吟游诗人', '德鲁伊', '邪术师', '法师'],
    'Feign Death': ['吟游诗人', '牧师', '德鲁伊', '法师'],
    'Find Familiar': ['法师'],
    'Find Steed': ['圣武士'],
    'Find Traps': ['牧师', '德鲁伊', '游侠'],
    'Find the Path': ['吟游诗人', '牧师', '德鲁伊'],
    'Finger of Death': ['术士', '邪术师', '法师'],
    'Fire Bolt': ['术士', '法师'],
    'Fire Shield': ['法师'],
    'Fire Storm': ['牧师', '德鲁伊', '术士'],
    'Fireball': ['术士', '法师'],
    'Flame Blade': ['德鲁伊'],
    'Flame Strike': ['牧师'],
    'Flaming Sphere': ['德鲁伊', '法师'],
    'Flesh to Stone': ['邪术师', '法师'],
    'Fly': ['术士', '邪术师', '法师', '奇械师'],
    'Fog Cloud': ['德鲁伊', '游侠', '术士', '法师'],
    'Forbiddance': ['牧师'],
    'Forcecage': ['吟游诗人', '邪术师', '法师'],
    'Foresight': ['吟游诗人', '德鲁伊', '邪术师', '法师'],
    'Freedom of Movement': ['吟游诗人', '牧师', '德鲁伊', '游侠', '奇械师'],
    'Friends': ['吟游诗人', '术士', '邪术师', '法师'],
    'Gaseous Form': ['术士', '邪术师', '法师', '奇械师'],
    'Gate': ['牧师', '术士', '法师'],
    'Geas': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '法师'],
    'Gentle Repose': ['牧师', '法师'],
    'Giant Insect': ['德鲁伊'],
    'Glibness': ['吟游诗人', '邪术师'],
    'Globe of Invulnerability': ['术士', '法师'],
    'Glyph of Warding': ['吟游诗人', '牧师', '法师', '奇械师'],
    'Goodberry': ['德鲁伊', '游侠'],
    'Grasping Vine': ['德鲁伊', '游侠'],
    'Grease': ['法师'],
    'Greater Invisibility': ['吟游诗人', '术士', '法师'],
    'Greater Restoration': ['吟游诗人', '牧师', '德鲁伊'],
    'Guardian of Faith': ['牧师'],
    'Guards and Wards': ['吟游诗人', '法师'],
    'Guidance': ['牧师', '德鲁伊'],
    'Guiding Bolt': ['牧师'],
    'Gust of Wind': ['德鲁伊', '术士', '法师'],
    'Hail of Thorns': ['游侠'],
    'Hallow': ['牧师'],
    'Hallucinatory Terrain': ['吟游诗人', '德鲁伊', '邪术师', '法师'],
    'Harm': ['牧师'],
    'Haste': ['术士', '法师', '奇械师'],
    'Heal': ['牧师', '德鲁伊'],
    'Healing Word': ['吟游诗人', '牧师', '德鲁伊'],
    'Heat Metal': ['吟游诗人', '德鲁伊'],
    'Hellish Rebuke': ['邪术师'],
    "Heroes' Feast": ['牧师', '德鲁伊'],
    'Heroism': ['吟游诗人', '圣武士'],
    'Hex': ['邪术师'],
    'Hold Monster': ['吟游诗人', '术士', '邪术师', '法师'],
    'Hold Person': ['吟游诗人', '牧师', '德鲁伊', '术士', '邪术师', '法师'],
    'Holy Aura': ['牧师'],
    'Hunger of Hadar': ['邪术师'],
    "Hunter's Mark": ['游侠'],
    'Hypnotic Pattern': ['吟游诗人', '术士', '邪术师', '法师'],
    'Ice Storm': ['德鲁伊', '术士', '法师'],
    'Identify': ['吟游诗人', '法师'],
    'Illusory Script': ['吟游诗人', '邪术师', '法师'],
    'Imprisonment': ['邪术师', '法师'],
    'Incendiary Cloud': ['术士', '法师'],
    'Inflict Wounds': ['牧师'],
    'Insect Plague': ['牧师', '德鲁伊', '术士'],
    'Invisibility': ['吟游诗人', '术士', '邪术师', '法师', '奇械师'],
    'Jump': ['德鲁伊', '游侠', '术士', '法师', '奇械师'],
    'Knock': ['吟游诗人', '术士', '法师'],
    'Legend Lore': ['吟游诗人', '牧师', '法师'],
    "Leomund's Secret Chest": ['法师', '奇械师'],
    "Leomund's Tiny Hut": ['吟游诗人', '法师'],
    'Lesser Restoration': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '游侠', '奇械师'],
    'Levitate': ['术士', '法师'],
    'Light': ['吟游诗人', '牧师', '术士', '法师'],
    'Lightning Arrow': ['游侠'],
    'Lightning Bolt': ['术士', '法师'],
    'Locate Animals or Plants': ['吟游诗人', '德鲁伊', '游侠'],
    'Locate Creature': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '游侠', '法师'],
    'Locate Object': ['吟游诗人', '牧师', '德鲁伊', '圣武士', '游侠', '法师'],
    'Longstrider': ['吟游诗人', '德鲁伊', '游侠', '法师', '奇械师'],
    'Mage Armor': ['术士', '法师'],
    'Mage Hand': ['吟游诗人', '术士', '邪术师', '法师'],
    'Magic Circle': ['牧师', '圣武士', '邪术师', '法师'],
    'Magic Jar': ['法师'],
    'Magic Missile': ['术士', '法师'],
    'Magic Mouth': ['吟游诗人', '法师'],
    'Magic Weapon': ['圣武士', '法师', '奇械师'],
    'Major Image': ['吟游诗人', '术士', '邪术师', '法师'],
    'Mass Cure Wounds': ['吟游诗人', '牧师', '德鲁伊'],
    'Mass Heal': ['牧师'],
    'Mass Healing Word': ['牧师'],
    'Mass Suggestion': ['吟游诗人', '术士', '邪术师', '法师'],
    'Maze': ['法师'],
    'Meld into Stone': ['牧师', '德鲁伊'],
    "Melf's Acid Arrow": ['法师'],
    'Mending': ['吟游诗人', '牧师', '德鲁伊', '术士', '法师'],
    'Message': ['吟游诗人', '术士', '法师'],
    'Meteor Swarm': ['术士', '法师'],
    'Mind Blank': ['吟游诗人', '法师'],
    'Minor Illusion': ['吟游诗人', '术士', '邪术师', '法师'],
    'Mirage Arcane': ['吟游诗人', '德鲁伊', '法师'],
    'Mirror Image': ['术士', '邪术师', '法师'],
    'Mislead': ['吟游诗人', '法师'],
    'Misty Step': ['术士', '邪术师', '法师'],
    'Modify Memory': ['吟游诗人', '法师'],
    'Moonbeam': ['德鲁伊'],
    "Mordenkainen's Faithful Hound": ['法师', '奇械师'],
    "Mordenkainen's Magnificent Mansion": ['吟游诗人', '法师'],
    "Mordenkainen's Private Sanctum": ['法师', '奇械师'],
    "Mordenkainen's Sword": ['吟游诗人', '法师'],
    'Move Earth': ['德鲁伊', '术士', '法师'],
    'Nondetection': ['吟游诗人', '游侠', '法师'],
    "Nystul's Magic Aura": ['法师'],
    "Otiluke's Freezing Sphere": ['法师'],
    "Otiluke's Resilient Sphere": ['法师', '奇械师'],
    "Otto's Irresistible Dance": ['吟游诗人', '法师'],
    'Pass Without Trace': ['德鲁伊', '游侠'],
    'Passwall': ['法师'],
    'Phantasmal Force': ['吟游诗人', '术士', '法师'],
    'Phantasmal Killer': ['法师'],
    'Phantom Steed': ['法师'],
    'Planar Ally': ['牧师'],
    'Planar Binding': ['吟游诗人', '牧师', '德鲁伊', '法师'],
    'Plane Shift': ['牧师', '德鲁伊', '术士', '邪术师', '法师'],
    'Plant Growth': ['吟游诗人', '德鲁伊', '游侠'],
    'Poison Spray': ['德鲁伊', '术士', '邪术师', '法师'],
    'Polymorph': ['吟游诗人', '德鲁伊', '术士', '法师'],
    'Power Word Heal': ['吟游诗人'],
    'Power Word Kill': ['吟游诗人', '术士', '邪术师', '法师'],
    'Power Word Stun': ['吟游诗人', '术士', '邪术师', '法师'],
    'Prayer of Healing': ['牧师'],
    'Prestidigitation': ['吟游诗人', '术士', '邪术师', '法师'],
    'Prismatic Spray': ['术士', '法师'],
    'Prismatic Wall': ['法师'],
    'Produce Flame': ['德鲁伊'],
    'Programmed Illusion': ['吟游诗人', '法师'],
    'Project Image': ['吟游诗人', '法师'],
    'Protection from Energy': ['牧师', '德鲁伊', '游侠', '术士', '法师', '奇械师'],
    'Protection from Evil and Good': ['牧师', '圣武士', '邪术师', '法师'],
    'Protection from Poison': ['牧师', '德鲁伊', '圣武士', '游侠', '奇械师'],
    'Purify Food and Drink': ['牧师', '德鲁伊', '圣武士'],
    'Raise Dead': ['吟游诗人', '牧师', '圣武士'],
    "Rary's Telepathic Bond": ['法师'],
    'Ray of Enfeeblement': ['邪术师', '法师'],
    'Ray of Frost': ['术士', '法师'],
    'Ray of Sickness': ['术士', '法师'],
    'Regenerate': ['吟游诗人', '牧师', '德鲁伊'],
    'Reincarnate': ['德鲁伊'],
    'Remove Curse': ['牧师', '圣武士', '邪术师', '法师'],
    'Resistance': ['牧师', '德鲁伊'],
    'Resurrection': ['吟游诗人', '牧师'],
    'Reverse Gravity': ['德鲁伊', '术士', '法师'],
    'Revivify': ['牧师', '圣武士', '奇械师'],
    'Rope Trick': ['法师', '奇械师'],
    'Sacred Flame': ['牧师'],
    'Sanctuary': ['牧师', '奇械师'],
    'Scorching Ray': ['术士', '法师'],
    'Scrying': ['吟游诗人', '牧师', '德鲁伊', '邪术师', '法师'],
    'Searing Smite': ['圣武士'],
    'See Invisibility': ['吟游诗人', '术士', '法师'],
    'Seeming': ['吟游诗人', '术士', '法师'],
    'Sending': ['吟游诗人', '牧师', '法师'],
    'Sequester': ['法师'],
    'Shapechange': ['德鲁伊', '法师'],
    'Shatter': ['吟游诗人', '术士', '邪术师', '法师'],
    'Shield': ['术士', '法师'],
    'Shield of Faith': ['牧师', '圣武士', '奇械师'],
    'Shillelagh': ['德鲁伊'],
    'Shocking Grasp': ['术士', '法师'],
    'Silence': ['吟游诗人', '牧师', '游侠'],
    'Silent Image': ['吟游诗人', '术士', '法师'],
    'Simulacrum': ['法师'],
    'Sleep': ['吟游诗人', '术士', '法师'],
    'Sleet Storm': ['德鲁伊', '术士', '法师'],
    'Slow': ['术士', '法师'],
    'Spare the Dying': ['牧师'],
    'Speak with Animals': ['吟游诗人', '德鲁伊', '游侠'],
    'Speak with Dead': ['吟游诗人', '牧师'],
    'Speak with Plants': ['吟游诗人', '德鲁伊', '游侠'],
    'Spider Climb': ['术士', '邪术师', '法师', '奇械师'],
    'Spike Growth': ['德鲁伊', '游侠'],
    'Spirit Guardians': ['牧师'],
    'Spiritual Weapon': ['牧师'],
    'Staggering Smite': ['圣武士'],
    'Stinking Cloud': ['吟游诗人', '术士', '法师'],
    'Stone Shape': ['牧师', '德鲁伊', '法师', '奇械师'],
    'Stoneskin': ['德鲁伊', '游侠', '术士', '法师', '奇械师'],
    'Storm of Vengeance': ['德鲁伊'],
    'Suggestion': ['吟游诗人', '术士', '邪术师', '法师'],
    'Sunbeam': ['德鲁伊', '术士', '法师'],
    'Sunburst': ['德鲁伊', '术士', '法师'],
    'Swift Quiver': ['游侠'],
    'Symbol': ['吟游诗人', '牧师', '法师'],
    "Tasha's Hideous Laughter": ['吟游诗人', '法师'],
    'Telekinesis': ['术士', '法师'],
    'Telepathy': ['法师'],
    'Teleport': ['吟游诗人', '术士', '法师'],
    'Teleportation Circle': ['吟游诗人', '术士', '法师'],
    "Tenser's Floating Disk": ['法师'],
    'Thaumaturgy': ['牧师'],
    'Thorn Whip': ['德鲁伊'],
    'Thunderous Smite': ['圣武士'],
    'Thunderwave': ['吟游诗人', '德鲁伊', '术士', '法师'],
    'Time Stop': ['术士', '法师'],
    'Tongues': ['吟游诗人', '牧师', '术士', '邪术师', '法师'],
    'Transport via Plants': ['德鲁伊'],
    'Tree Stride': ['德鲁伊', '游侠'],
    'True Polymorph': ['吟游诗人', '邪术师', '法师'],
    'True Resurrection': ['牧师', '德鲁伊'],
    'True Seeing': ['吟游诗人', '牧师', '术士', '邪术师', '法师'],
    'True Strike': ['吟游诗人', '术士', '邪术师', '法师'],
    'Tsunami': ['德鲁伊'],
    'Unseen Servant': ['吟游诗人', '邪术师', '法师'],
    'Vampiric Touch': ['邪术师', '法师'],
    'Vicious Mockery': ['吟游诗人'],
    'Wall of Fire': ['德鲁伊', '术士', '法师'],
    'Wall of Force': ['法师'],
    'Wall of Ice': ['法师'],
    'Wall of Stone': ['德鲁伊', '术士', '法师'],
    'Wall of Thorns': ['德鲁伊'],
    'Warding Bond': ['牧师'],
    'Water Breathing': ['德鲁伊', '游侠', '术士', '法师', '奇械师'],
    'Water Walk': ['牧师', '德鲁伊', '游侠', '术士', '奇械师'],
    'Web': ['术士', '法师'],
    'Weird': ['法师'],
    'Wind Walk': ['德鲁伊'],
    'Wind Wall': ['德鲁伊', '游侠'],
    'Wish': ['术士', '法师'],
    'Witch Bolt': ['术士', '邪术师', '法师'],
    'Word of Recall': ['牧师'],
    'Wrathful Smite': ['圣武士'],
    'Zone of Truth': ['吟游诗人', '牧师', '圣武士'],
}
